### ISSUE TITLE
PRUSA SLICER Error running command {POWER_LOSS_RESUME} 

### ISSUE THREAD

**Issue by zeitas** [The--Captain/plr-klipper#4]
22:10
Unknown command:"RESPOND"
PRUSA SLICER Error running command {POWER_LOSS_RESUME}

**Comment by The--Captain** [comment]
without a lot more information I cannot even begin to help help you solve this issue. You can start by posting your printer.cfg and any other relevant configuration files

**Comment by The--Captain** [comment]
With further consideration it seems very likely that you need a [respond] line in your plr.cfg.

It seems like this line is missing, and will cause errors for those who do not have respond already enabled.

You can add that line manually or just download/update your code from this repository, since the fix has been committed.
